### ISSUE TITLE
600.0.0 Release build using Swift 5

### ISSUE THREAD

**Issue by sebastianv1** [square/swift-syntax-prebuilt#10]
Would it be possible to build 600.0.0 with Xcode 16 and Swift 5? For example moving from building from sources in `600.0.0` to prebuilt incurs the following compilation error (still on Xcode 15.4 for instance or using Swift 5 version mode on 16)
```
error: failed to build module 'SwiftSyntax'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)', while this compiler is 'Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)'). Please select a toolchain which matches the SDK.
```

**Comment by luispadron** [comment]
Hi! I can look into this soon

**Comment by luispadron** [comment]
So this wont be possible, given `swift-syntax` is dependent on a specific Swift compiler version (which is why they tag releases like `600.0.0`), even if we force the swift version to `5` we end up failing to find some Swift 6 only types:


```
external/swift-syntax~/arm64/SwiftSyntax.private.swiftinterface:27036:61: error: no type named 'BitwiseCopyable' in module 'Swift'
@_spi(RawSyntax) extension SwiftSyntax.RawTokenKind : Swift.BitwiseCopyable {}
                                                            ^
```
